"""Remove payouts table

Revision ID: 01d999fa1a43
Revises: 92aee86e34c1
Create Date: 2026-03-07 20:33:29.468323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d999fa1a43'
down_revision = '92aee86e34c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payouts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('payout_id', sa.INTEGER(), nullable=False),
    sa.Column('companion_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('requested_at', sa.DATETIME(), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('processed_by', sa.INTEGER(), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['companion_id'], ['companion_profiles.companion_id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payout_id')
    )
    # ### end Alembic commands ###
