"""Add reply fields to reviews

Revision ID: 1fb7584013c4
Revises: 5ca64be27321
Create Date: 2026-03-05 20:33:19.691309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb7584013c4'
down_revision = '5ca64be27321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_favorites_customer_id', 'customer_profiles', ['customer_id'], ['customer_id'])
        batch_op.create_foreign_key('fk_favorites_companion_id', 'companion_profiles', ['companion_id'], ['companion_id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('replied_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('replied_at')
        batch_op.drop_column('reply')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('_favorites_old_20260305_1',
    sa.Column('favorite_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('companion_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_table('_favorites_old_20260305',
    sa.Column('favorite_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('companion_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['companion_id'], ['companion_profiles.companion_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    # ### end Alembic commands ###
