"""add cover_photo_url to companion_profiles

Revision ID: 523024eab124
Revises: 1fb7584013c4
Create Date: 2026-03-05 21:23:25.895277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523024eab124'
down_revision = '1fb7584013c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion_profiles', schema=None) as batch_op:
        batch_op.drop_column('cover_photo_url')

    # ### end Alembic commands ###
