"""Add status to User, auto-sanctions

Revision ID: 5ca64be27321
Revises: eb8621e45355
Create Date: 2026-03-01 02:25:15.975508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca64be27321'
down_revision = 'eb8621e45355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_requested_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'AWAITING_INFO', 'RESOLVED', name='reportstatusenum'),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'BANNED', name='userstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'AWAITING_INFO', 'RESOLVED', name='reportstatusenum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.drop_column('info_requested_at')

    # ### end Alembic commands ###
