"""empty message

Revision ID: 92aee86e34c1
Revises: bf8ac7d8dc4b
Create Date: 2026-03-07 20:06:46.275291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92aee86e34c1'
down_revision = 'bf8ac7d8dc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('payouts',
    sa.Column('payout_id', sa.Integer(), nullable=False),
    sa.Column('companion_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'CANCELLED', name='payoutstatusenum'), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['companion_id'], ['companion_profiles.companion_id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payout_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewstatusenum'), nullable=True))
        batch_op.add_column(sa.Column('moderated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('moderated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reviews_moderated_by_users', 'users', ['moderated_by'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_moderated_by_users', type_='foreignkey')
        batch_op.drop_column('moderated_by')
        batch_op.drop_column('moderated_at')
        batch_op.drop_column('status')

    op.drop_table('payouts')
    op.drop_table('audit_logs')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
