"""add cover_photo to customer profile

Revision ID: bf8ac7d8dc4b
Revises: 523024eab124
Create Date: 2026-03-05 21:58:15.143220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8ac7d8dc4b'
down_revision = '523024eab124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.drop_column('cover_photo')

    # ### end Alembic commands ###
